### ISSUE TITLE
UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!

### ISSUE THREAD

**Issue by yincangshiwei** [halfzm/ProPainter-Webui#6]
/root/ProPainter-Webui/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
Traceback (most recent call last):
  File "/root/ProPainter-Webui/app.py", line 387, in <module>
    seg_track_app()
  File "/root/ProPainter-Webui/app.py", line 380, in seg_track_app
    app.queue(concurrency_count=1)
TypeError: Blocks.queue() got an unexpected keyword argument 'concurrency_count'

**Comment by WM-1857** [comment]
> /root/ProPainter-Webui/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only! warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!") Traceback (most recent call last): File "/root/ProPainter-Webui/app.py", line 387, in seg_track_app() File "/root/ProPainter-Webui/app.py", line 380, in seg_track_app app.queue(concurrency_count=1) TypeError: Blocks.queue() got an unexpected keyword argument 'concurrency_count'

have you fixed it? I run into the same problem

**Comment by deepConnectionism** [comment]
groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")

我遇到了同样的错误！

**Comment by hare321** [comment]
(propainter) PS C:\Users\mouse\ProPainter-Webui> python app.py
C:\Users\mouse\miniconda3\envs\propainter\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
C:\Users\mouse\ProPainter-Webui\groundingdino\models\GroundingDINO\ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
Traceback (most recent call last):)
  File "C:\Users\mouse\ProPainter-Webui\app.py", line 387, in <module>
    seg_track_app()
  File "C:\Users\mouse\ProPainter-Webui\app.py", line 380, in seg_track_app
    app.queue(concurrency_count=1)
  File "C:\Users\mouse\miniconda3\envs\propainter\lib\site-packages\gradio\blocks.py", line 2133, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().
(propainter) PS C:\Users\mouse\ProPainter-Webui>

我也遇到了同样错误！
